# syntax=docker/dockerfile:1
FROM ubuntu
ARG VERSION=0.68.0
ARG CHECKSUM=sha256:3cf934477f4fb1ee9e19e49c31fb33f5ffe3283300076f59afad8b8ccf1e1621

COPY script.sh .

ADD --unpack=true --checksum=${CHECKSUM} https://github.com/fatedier/frp/releases/download/v${VERSION}/frp_${VERSION}_linux_amd64.tar.gz /tmp/frp

RUN mv /tmp/frp/frp_${VERSION}_linux_amd64 /frp
